owner: prokerala
repo: uptime

# Add your sites here
sites:
  - name: Prokerala
    url: https://www.prokerala.com

status-website:
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Prokerala
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
assignees: # Users to assign downtime issues (optional)
  - JoyceBabu
  - akhil.p
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
